source 'https://github.com/CocoaPods/Specs.git'

target 'SimpleFeedback', :exclusive => true do
  pod "SimpleFeedback", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SimpleFeedback", :path => "../"

  
end
